"use client";

import { ArrowLeft, BarChart3, ChevronDown, TrendingUp } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

const athletes = [{ name: "Deneme Öğrencisi", css: "1:32", spm: 42, dps: 2.04, split: "0:43", recovery: 82 }, { name: "Selin Kaya", css: "1:28", spm: 46, dps: 1.98, split: "0:41", recovery: 88 }, { name: "Mert Aydın", css: "1:36", spm: 39, dps: 2.12, split: "0:45", recovery: 76 }];
const metrics = ["Tempo / 100M", "SPM", "Stroke Length", "DPS", "CSS", "Split", "Recovery"];

export default function ComparePage() {
  const [selected, setSelected] = useState([athletes[0].name, athletes[1].name]);
  const [distance, setDistance] = useState("200M");
  const [stroke, setStroke] = useState("FREESTYLE");
  const rows = useMemo(() => athletes.filter((athlete) => selected.includes(athlete.name)), [selected]);
  function toggle(name: string) { setSelected((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name]); }
  return <main className="module-page compare-page"><div className="detail-breadcrumb"><Link href="/swimbase"><ArrowLeft size={13} /> SWIMBASE</Link><span>→ COMPARE</span></div><header className="module-heading"><div><div className="eyebrow"><BarChart3 size={13} /> SWIMBASE / PERFORMANCE COMPARE</div><h1>ATHLETE <em>COMPARE</em></h1><p>İki veya daha fazla sporcuyu aynı mesafe ve stil bağlamında karşılaştır.</p></div></header><section className="compare-controls"><label>DISTANCE<select value={distance} onChange={(event) => setDistance(event.target.value)}><option>50M</option><option>100M</option><option>200M</option><option>400M</option></select><ChevronDown size={13} /></label><label>STROKE<select value={stroke} onChange={(event) => setStroke(event.target.value)}><option>FREESTYLE</option><option>BACKSTROKE</option><option>BREASTSTROKE</option><option>BUTTERFLY</option></select><ChevronDown size={13} /></label><div className="athlete-selector"><span>ATHLETES</span>{athletes.map((athlete) => <button type="button" className={selected.includes(athlete.name) ? "active" : ""} onClick={() => toggle(athlete.name)} key={athlete.name}>{athlete.name}</button>)}</div></section><section className="compare-chart"><div className="compare-chart-header"><span><TrendingUp size={15} /> PERFORMANCE TREND / {distance} {stroke}</span><b>LAST 30 DAYS</b></div><div className="trend-bars">{rows.map((athlete, index) => <div className="trend-athlete" key={athlete.name}><strong>{athlete.name}</strong><div><i style={{ height: `${72 + index * 13}%` }} /><i style={{ height: `${54 + index * 18}%` }} /><i style={{ height: `${84 - index * 9}%` }} /><i style={{ height: `${64 + index * 11}%` }} /><i style={{ height: `${91 - index * 14}%` }} /></div><small>W1&nbsp;&nbsp;&nbsp; W2&nbsp;&nbsp;&nbsp; W3&nbsp;&nbsp;&nbsp; W4&nbsp;&nbsp;&nbsp; W5</small></div>)}</div></section><section className="compare-table"><div className="compare-table-row compare-table-head"><span>METRIC</span>{rows.map((athlete) => <span key={athlete.name}>{athlete.name}</span>)}</div>{[["Tempo / 100M", "css"], ["SPM", "spm"], ["Stroke Length", "dps"], ["DPS", "dps"], ["CSS", "css"], ["Split", "split"], ["Recovery", "recovery"]].map(([label, key]) => <div className="compare-table-row" key={label}><b>{label}</b>{rows.map((athlete) => <span key={athlete.name}>{athlete[key as keyof typeof athlete]}{key === "recovery" ? "%" : ""}</span>)}</div>)}</section><div className="compare-insights"><div><b>STRENGTH SIGNAL</b><p>{rows[0]?.name ?? "Sporcu"} daha yüksek DPS ile kulaç ekonomisi avantajı gösteriyor.</p></div><div><b>DEVELOPMENT SIGNAL</b><p>SPM ve CSS birlikte izlenmeli; yüksek frekans tek başına daha iyi performans anlamına gelmez.</p></div></div></main>;
}
