"use client";

import { Activity, Award, Edit3, UserRound } from "lucide-react";
import { useState } from "react";

const personalBests = [["50 m Serbest", "00:27.84", "-0.42 sn"], ["100 m Serbest", "01:01.20", "-1.18 sn"], ["200 m Serbest", "02:14.60", "+0.08 sn"], ["100 m Kelebek", "01:09.45", "-0.63 sn"]];

export default function ProfilePage() {
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState("Deniz Yüzücü");
  return <main className="module-page profile-page"><header className="module-heading"><div><div className="eyebrow"><UserRound size={13} /> SWIMBASE / SPORCU PROFİLİ</div><h1>PERFORMANS <em>MERKEZİ</em></h1><p>Lisans bilgilerin, kişisel en iyi derecelerin ve gelişim sinyallerin burada düzenli kalır.</p></div><div className="sync-badge"><i /> PROFİL CİHAZDA</div></header><div className="profile-layout"><section className="profile-card"><div className="profile-avatar"><UserRound size={32} /></div>{editing ? <input className="profile-name-input" value={name} onChange={(event) => setName(event.target.value)} aria-label="Sporcu adı" /> : <h2>{name}</h2>}<span className="profile-role">SPORCU · AÇIK SU / HAVUZ</span><button type="button" className="profile-edit" onClick={() => setEditing((value) => !value)}><Edit3 size={14} /> {editing ? "KAYDET" : "PROFİLİ DÜZENLE"}</button><div className="profile-facts"><span><b>KATEGORİ</b> Gençler</span><span><b>LİSANS</b> TR-2026-0418</span><span><b>HEDEF</b> 100 m serbest</span></div></section><section className="performance-card"><div className="section-title"><span><Activity size={14} /> 8 HAFTALIK GELİŞİM</span><small>CSS / 100 M</small></div><div className="performance-chart" aria-label="Sekiz haftalık CSS gelişim grafiği">{[74, 68, 72, 61, 58, 53, 49, 44].map((height, index) => <div className="chart-column" key={index}><i style={{ height: `${height}%` }} /><small>H{index + 1}</small></div>)}</div><div className="trend-summary"><strong>1:32 <small>CSS</small></strong><span><Award size={15} /> Son 8 haftada <b>6 sn</b> gelişim</span></div></section></div><section className="pb-section"><div className="section-title"><span><Award size={14} /> KİŞİSEL EN İYİLER</span><small>RESMİ SONUÇLAR</small></div><div className="pb-table"><div className="pb-head"><span>BRANŞ</span><span>DERECE</span><span>SON DEĞİŞİM</span></div>{personalBests.map(([event, time, change]) => <div className="pb-row" key={event}><strong>{event}</strong><b>{time}</b><span className={change.startsWith("+") ? "neutral" : "positive"}>{change}</span></div>)}</div></section></main>;
}
