"use client";

import { BookOpen, Database, ExternalLink, Search, Sparkles, Waves } from "lucide-react";
import { useMemo, useState } from "react";

type KnowledgeBaseProps = { onAsk: (question: string) => void; initialQuery?: string };
type Article = { category: string; title: string; summary: string; detail: string; tag: string; tone: string; prompts: string[] };
const articles: Article[] = [
  { category: "BIOMECHANICS", title: "Freestyle: High-Elbow Catch", summary: "Yüksek dirsek yakalama, giriş açısı ve omuz rotasyonunu suyu daha geride tutacak şekilde birleştirme.", detail: "El suya omuz çizgisi önünde, parmak uçları hafif aşağı bakacak şekilde girer. Önkolu erken dikey konuma getirirken dirseği yüzeye yakın ve sabit tutmak, avuç içi ile önkolu etkili bir itiş yüzeyine dönüştürür. Omuz iç rotasyonunu zorlamak yerine gövde rotasyonunu yaklaşık 35-45 derece aralığında kullan; ağrı, hareket açıklığının sınırı değildir.", tag: "TECH / 06 MIN", tone: "cyan", prompts: ["High-elbow catch için 3 drill öner", "Giriş açımı kaç derece olmalı?"] },
  { category: "BIOMECHANICS", title: "Four-Stroke Drag Atlas", summary: "Serbest, kelebek, sırt ve kurbağalamada frontal alan, streamline ve pozisyonel sürükleme karşılaştırması.", detail: "Sürükleme kuvveti pratikte hızın karesiyle artar; bu nedenle baş, kalça ve ayakların aynı akış çizgisinde kalması küçük bir teknik farkı büyük enerji tasarrufuna dönüştürür. Serbest ve sırtta yatay streamline; kelebekte dalga sürüklemesini azaltan ritmik gövde dalgası; kurbağalamada ise toparlanma sırasında dar profil ve güçlü streamline önceliklidir. Drag coefficient tek başına değil, hız ve frontal alanla birlikte yorumlanmalıdır.", tag: "ATLAS / 12 MIN", tone: "violet", prompts: ["Drag coefficient nasıl düşürülür?", "Dört stili sürükleme açısından karşılaştır"] },
  { category: "BIOMECHANICS", title: "Butterfly, Back & Breaststroke Angles", summary: "Kelebekte dalga aktarımı, sırtta kalça hattı ve kurbağalamada giriş/toparlanma açıları için uygulama rehberi.", detail: "Kelebekte göğüs baskısı kalçaya, kalça baskısı ayak vuruşuna sıralı aktarılmalıdır. Sırtta baş nötr, kalça su yüzeyine yakın ve omuz rotasyonu kontrollü olmalıdır. Kurbağalamada ellerin ileri uzanışı dar bir ok başı oluşturmalı; dizler çekişte kalça genişliğini gereksiz aşmamalıdır. Video analizinde açıları tek kareden değil, aynı fazın üç ardışık karesinden doğrula.", tag: "TECH / 08 MIN", tone: "gold", prompts: ["Sırtta kalça düşüşünü nasıl düzeltirim?", "Kurbağalama toparlanma açısını analiz et"] },
  { category: "PHYSIOLOGY", title: "CSS: Critical Swim Speed", summary: "İki zamanlı testten CSS hesaplama, pace dönüşümü ve antrenman zonlarına güvenli başlangıç.", detail: "Pratik CSS formülü: CSS = (mesafe2 - mesafe1) / (zaman2 - zaman1). Örneğin 400 m ve 200 m test süreleri saniyeye çevrilir; fark mesafe farkına bölünür ve m/s elde edilir, ardından 100 m pace'e dönüştürülür. Testler aynı gün, tam ısınma sonrası ve benzer koşullarda uygulanmalı; CSS bir yarış tahmini değil, eşik çevresi yüklenmeyi düzenleyen antrenman referansıdır.", tag: "METHOD / 09 MIN", tone: "coral", prompts: ["CSS'imi 400/200 testiyle hesapla", "CSS pace'imin EN2 karşılığı nedir?"] },
  { category: "PHYSIOLOGY", title: "Lactate Threshold: EN1 / EN2 / EN3", summary: "Aerobik temel, eşik ve yüksek yoğunluk bölgelerini laktat davranışıyla ilişkilendirme.", detail: "EN1 düşük-orta yoğunlukta teknik kalitesi, aerobik hacmi ve toparlanmayı destekler. EN2 CSS çevresinde kontrollü zorlanma, sürdürülebilir tempo ve laktat temizleme kapasitesini geliştirir. EN3 kısa tekrarlar, yarış temposu ve yüksek laktat toleransı içindir. Bölge sınırları yüzücünün test verisi, nabız tepkisi ve set sonunda tekniğin bozulup bozulmaması birlikte değerlendirilerek kişiselleştirilmelidir.", tag: "PHYSIOLOGY / 08 MIN", tone: "coral", prompts: ["EN1-EN2-EN3 için örnek set yaz", "Laktat yükselince tekniği nasıl korurum?"] },
  { category: "PHYSIOLOGY", title: "VO2max Development & Tapering", summary: "VO2max uyaranı, toparlanma sinyalleri ve yarış öncesi hacim azaltma sürecini planlama.", detail: "VO2max gelişimi yüksek aerobik güç tekrarları, yeterli dinlenme ve haftalık yükün kademeli artışıyla oluşur; her yoğun set yarışa yakın yapılmamalıdır. Taper döneminde hacim genellikle azaltılır, kısa kalite tekrarları ve teknik hız korunur. Yüzücünün uyku, sabah nabzı ve set sonrası algılanan zorluk verileri, takvimden daha iyi bir toparlanma göstergesi olabilir.", tag: "METHOD / 10 MIN", tone: "green", prompts: ["14 günlük taper planı oluştur", "VO2max setini yaş grubuma uyarla"] },
  { category: "TRAINING", title: "SPM, Sets & Drills by Age", summary: "Yaş gruplarına göre kulaç frekansı yönetimi, set mimarisi ve tekniği koruyan drill seçimi.", detail: "Genç yüzücülerde SPM hedefi tek başına artırılmamalı; önce suya giriş, yakalama ve ritim kalitesi sabitlenmelidir. Setler teknik hazırlık, aerobik/threshold ana seti ve gevşek yüzme ile üç parçaya ayrılabilir. Fist drill yakalamayı, single-arm drill gövde rotasyonunu, 6-kick switch ise streamline ve nefes zamanlamasını görünür kılar. Drill, tam kulaçtan kopuk değil, aynı günün ana hedefini prova eden kısa bir araç olmalıdır.", tag: "COACHING / 11 MIN", tone: "violet", prompts: ["12 yaş grubu için SPM seti yaz", "High elbow için drill sıralaması ver"] },
  { category: "RACING", title: "World Aquatics Records / 2026", summary: "Güncel dünya rekorları, split analizi, kulvar etkisi ve yarış temposu referansları.", detail: "Rekor karşılaştırmasında yalnızca final zamanı değil, ilk 50/100 split'i, dönüş hızı, breakout mesafesi ve son bölümdeki hız kaybı incelenmelidir. Kulvar koşulları ve yarış formatı sonucu etkileyebilir. Bu paneldeki kayıt rozeti güncel veri kaynağına bağlanacak şekilde tasarlanmıştır; antrenman kararlarında resmi World Aquatics kaydının tarihini ve kısa kulvar/uzun kulvar ayrımını mutlaka doğrula.", tag: "LIVE DATA / UPDATED", tone: "gold", prompts: ["200 serbest splitlerini nasıl analiz ederim?", "World Aquatics kaydını antrenmana çevir"] },
];
const categories = ["ALL ENTRIES", "BIOMECHANICS", "PHYSIOLOGY", "TRAINING", "RACING"];

export default function KnowledgeBase({ onAsk, initialQuery = "" }: KnowledgeBaseProps) {
  const [query, setQuery] = useState(initialQuery);
  const [category, setCategory] = useState("ALL ENTRIES");
  const [expanded, setExpanded] = useState<string | null>(null);
  const filtered = useMemo(() => articles.filter((article) => (category === "ALL ENTRIES" || article.category === category) && `${article.title} ${article.summary}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  const quickPrompts = ["CSS nasıl hesaplanır?", "Serbestte omuz rotasyonu", "EN1 / EN2 / EN3 farkı", "Yarış öncesi taper planı"];

  return (
    <section className="module-page knowledge-page">
      <header className="module-heading"><div><div className="eyebrow"><BookOpen size={13} /> ASTRA-G7 / RESEARCH CORE</div><h1>SWIM <em>KNOWLEDGE BASE</em></h1><p>Yüzme bilimi, yarış verisi ve antrenman metodolojisi tek yaşayan kütüphanede.</p></div><div className="sync-badge sync-live"><i /> LAST SYNC: TODAY - WORLD AQUATICS UPDATED</div></header>
      <div className="knowledge-toolbar"><div className="knowledge-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search technique, physiology, records..." /></div><div className="category-tabs">{categories.map((item) => <button type="button" className={category === item ? "active" : ""} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div></div>
      <div className="quick-prompts"><span><Sparkles size={13} /> QUICK PROMPTS</span>{quickPrompts.map((prompt) => <button type="button" key={prompt} onClick={() => onAsk(`Knowledge Base quick question: ${prompt}`)}>{prompt}</button>)}</div>
      <div className="knowledge-layout"><div className="article-grid">{filtered.map((article) => <article className={`knowledge-card ${article.tone}`} key={article.title}><div className="article-meta"><span>{article.category}</span><small>{article.tag}</small></div><h2>{article.title}</h2><p>{article.summary}</p><div className="article-actions"><button type="button" onClick={() => setExpanded(expanded === article.title ? null : article.title)}>{expanded === article.title ? "CLOSE GUIDE" : "READ GUIDE"}</button><button type="button" onClick={() => onAsk(`Knowledge Base: ${article.title}. Context: ${article.detail} Question: Give an expert and athlete-friendly answer.`)}>ASK ASTRA-G7 <ExternalLink size={13} /></button></div>{expanded === article.title && <div className="article-detail"><p>{article.detail}</p><div className="article-prompts">{article.prompts.map((prompt) => <button type="button" key={prompt} onClick={() => onAsk(`Knowledge Base: ${article.title}. ${article.detail} User question: ${prompt}`)}>{prompt}</button>)}</div></div>}</article>)}{filtered.length === 0 && <div className="empty-state">No entries match this query.</div>}</div><aside className="engine-status"><div className="engine-icon"><Database size={20} /></div><span className="eyebrow"><Sparkles size={12} /> MASTER ENGINE STATUS</span><h2>Knowledge is live.</h2><p>Daily source checks combine World Aquatics records, peer-reviewed swim science and the athlete memory layer.</p><div className="engine-stat"><span>INDEXED ENTRIES</span><strong>2,841</strong></div><div className="engine-stat"><span>LAST SOURCE CHECK</span><strong>06:40 UTC</strong></div><div className="engine-stat"><span>ASTRA LINK</span><strong className="green-text">CONNECTED</strong></div><div className="source-list"><span><Waves size={13} /> WORLD AQUATICS</span><span><BookOpen size={13} /> SPORTS SCIENCE INDEX</span></div></aside></div>
    </section>
  );
}
